services:
  aitranslator:
    build: .
    restart: unless-stopped
    expose:
      - "7000"
    volumes:
      - ./data:/app/data
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aitranslator.rule=Host(`aitranslator.yourdomain.com`)"
      - "traefik.http.routers.aitranslator.tls=true"
      - "traefik.http.routers.aitranslator.tls.certresolver=letsencrypt"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.compose:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
      - web
    depends_on:
      - aitranslator

networks:
  internal:
    internal: true
  web:
    external: false

volumes:
  caddy_data:
  caddy_config: 