services:
  aitranslator:
    build:
      context: .
      target: production
    restart: unless-stopped
    ports:
      - "7000:7000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production 