version: '3.8'

services:
  addon:
    build: .
    restart: unless-stopped
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./subtitles:/app/subtitles
    ports:
      - "3000:3000"
      - "7000:7000"
    networks:
      - addon-network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - addon-network
    depends_on:
      - addon

volumes:
  caddy_data:
  caddy_config:

networks:
  addon-network:
    driver: bridge 