services:
  redis-aitranslator:
    container_name: aitranslator-database
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  aitranslator:
    container_name: aitranslator
    build:
      context: .
      target: production
    ports:
      - "7000:7000"
    volumes:
      - ./data:/app/data
      - ./langs:/app/langs
      - ./subtitles:/app/subtitles
    environment:
      - DEBUG=stremio:*
      - NODE_ENV=production
      - REDIS_URL=redis://redis-aitranslator:6379
    depends_on:
      redis-aitranslator:
        condition: service_healthy
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
