version: '3.8'

services:
  aitranslator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stremio-aitranslator
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DEBUG=stremio:*
      - DEBUG_COLORS=true
      - DEBUG_DEPTH=10
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./subtitles:/app/subtitles
      - ./logs:/app/logs
      - ./credentials.json:/app/credentials.json
    ports:
      - "11470:11470"  # Stremio addon port
      - "9229:9229"    # Node.js debugging port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11470/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development service with additional debugging tools
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stremio-aitranslator-dev
    restart: "no"
    environment:
      - NODE_ENV=development
      - DEBUG=stremio:*,app:*
      - DEBUG_COLORS=true
      - DEBUG_DEPTH=10
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "11470:11470"
      - "9229:9229"
    command: pnpm run dev
    healthcheck:
      disable: true 