version: '3.8'

services:
  app:
    build: .
    container_name: stremio-aitranslator
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    volumes:
      - subtitle-cache:/app/subtitles
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  subtitle-cache:
    name: aitranslator-subtitles
  logs:
    name: aitranslator-logs
