version: '3.8'

services:
  app:
    build: .
    container_name: stremio-aitranslator
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - CACHE_ENABLED=true
      - CACHE_TTL=86400
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
